version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - db

    db:
      image: postgres:15-alpine
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydatabase
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT:EMAIL: rsolm72@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db

volumes:
  postgres_data: